name: enjin_wallet_daemon
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  download_assets: ^3.1.1
  flutter_svg: ^2.0.7
  xterm: ^3.5.0
  loading_animation_widget: ^1.2.0+4
  dio: ^5.3.3
  convert: ^3.1.1
  lottie: ^2.7.0
  sembast: ^3.5.0+1
  encrypt: ^5.0.0
  crypto: ^3.0.0
  get_it: ^7.6.4
  smooth_page_indicator: ^1.1.0
  window_manager: ^0.3.7
  onboarding_overlay: ^3.2.1
  get: ^4.6.6
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  outline_gradient_button: ^2.0.0+1
  intl: ^0.18.0
  aligned_dialog: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "lib/assets/enjin_logo.png"
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/animations/
    - lib/assets/
    - lib/fonts/
    - config.json

  fonts:
    - family: Hauora
      fonts:
         - asset: lib/fonts/Hauora-Bold.ttf
           weight: 700
         - asset: lib/fonts/Hauora-ExtraBold.ttf
           weight: 800
         - asset: lib/fonts/Hauora-ExtraLight.ttf
           weight: 200
         - asset: lib/fonts/Hauora-Light.ttf
           weight: 300
         - asset: lib/fonts/Hauora-Medium.ttf
           weight: 500
         - asset: lib/fonts/Hauora-Regular.ttf
           weight: 400
         - asset: lib/fonts/Hauora-SemiBold.ttf
           weight: 600
    - family: Inter
      fonts:
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
    - family: Aldrich
      fonts:
        - asset: assets/fonts/AldrichRegular.ttf
          weight: 400
    - family: Genos
      fonts:
        - asset: assets/fonts/Genos-Bold.ttf
          weight: 700
