name: daemon
description: Enjin Wallet Daemon for Windows, macOS, and Linux
publish_to: 'none'
version: 2.1.1+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.4.0
  path: ^1.9.0
  path_provider: ^2.1.3
  download_assets: ^3.2.0
  flutter_svg: ^2.0.10+1
  xterm: ^4.0.0
  dio: ^5.4.3+1
  convert: ^3.1.1
  lottie: ^3.1.2
  sembast: ^3.7.1+2
  encrypt: ^5.0.3
  crypto: ^3.0.3
  window_manager: ^0.3.9
  get: ^4.6.6
  outline_gradient_button: ^2.0.1+1
  intl: ^0.19.0
  aligned_dialog: ^0.0.7
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "lib/assets/enjin_logo.png"
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/animations/
    - config.json

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
    - family: Aldrich
      fonts:
        - asset: assets/fonts/AldrichRegular.ttf
          weight: 400
    - family: Genos
      fonts:
        - asset: assets/fonts/Genos-Bold.ttf
          weight: 700
