name: enjin_wallet_daemon
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  uuid: ^4.1.0
  shared_preferences: ^2.2.2
  path: ^1.8.3
  path_provider: ^2.1.1
  device_info_plus: ^9.1.0
  download_assets: ^3.1.1
  flutter_onboarding_slider: ^1.0.11
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "lib/assets/enjin_logo.png"
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/fonts/
    - wallet/linux/
    - wallet/macos-apple/
    - wallet/macos-intel/
    - wallet/windows/
    - config.json

  fonts:
    - family: Hauora
      fonts:
         - asset: lib/fonts/Hauora-Bold.ttf
           weight: 700
         - asset: lib/fonts/Hauora-ExtraBold.ttf
           weight: 800
         - asset: lib/fonts/Hauora-ExtraLight.ttf
           weight: 200
         - asset: lib/fonts/Hauora-Light.ttf
           weight: 300
         - asset: lib/fonts/Hauora-Medium.ttf
           weight: 500
         - asset: lib/fonts/Hauora-Regular.ttf
           weight: 400
         - asset: lib/fonts/Hauora-SemiBold.ttf
           weight: 600