name: daemon
description: Enjin Wallet Daemon is a cross-platform desktop application that allows game developers to interact with the Enjin Platform
publish_to: 'none'
version: 2.3.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1
  path: ^1.9.1
  path_provider: ^2.1.5
  background_downloader: ^8.9.4
  archive: ^4.0.2
  flutter_svg: ^2.0.17
  xterm: ^4.0.0
  dio: ^5.8.0+1
  convert: ^3.1.2
  lottie: ^3.3.1
  sembast: ^3.8.3
  encrypt: ^5.0.3
  crypto: ^3.0.6
  window_manager: ^0.4.3
  get: ^4.6.6
  outline_gradient_button: ^2.0.1+1
  intl: ^0.20.2
  aligned_dialog: ^0.0.7
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  image_path: "lib/assets/enjin_logo.png"
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/animations/
    - config.json

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
    - family: Aldrich
      fonts:
        - asset: assets/fonts/AldrichRegular.ttf
          weight: 400
    - family: Genos
      fonts:
        - asset: assets/fonts/Genos-Bold.ttf
          weight: 700
