name: Flutter CI

on: push

jobs:
  build-and-release-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install dependencies
        run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

      - name: Install project dependencies
        run: flutter pub get

      - name: Build artifacts
        run: flutter build linux --release

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: EnjinWalletDaemon-${{github.ref_name}}-linux.zip
          directory: build/linux/x64/release/bundle

      - name: Upload artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: EnjinWalletDaemon-${{github.ref_name}}-linux.zip
          path: build/linux/x64/release/bundle/EnjinWalletDaemon-${{github.ref_name}}-linux.zip

      - name: Linux Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/linux/x64/release/bundle/EnjinWalletDaemon-${{github.ref_name}}-linux.zip

  build-and-release-windows:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install project dependencies
        run: flutter pub get

      - name: Build artifacts
        run: flutter build windows --release

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: EnjinWalletDaemon-${{github.ref_name}}-windows.zip
          directory: build/windows/runner/Release

      - name: Upload artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: EnjinWalletDaemon-${{github.ref_name}}-windows.zip
          path: build/linux/x64/release/bundle/EnjinWalletDaemon-${{github.ref_name}}-windows.zip

      - name: Windows Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/windows/runner/Release/EnjinWalletDaemon-${{github.ref_name}}-windows.zip

  build-and-release-macos:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install project dependencies
        run: flutter pub get

      - name: Build artifacts
        run: flutter build macos --release

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: EnjinWalletDaemon-${{github.ref_name}}-macos.zip
          directory: build/macos/Build/Products/Release

      - name: Upload artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: EnjinWalletDaemon-${{github.ref_name}}-macos.zip
          path: build/linux/x64/release/bundle/EnjinWalletDaemon-${{github.ref_name}}-macos.zip

      - name: macOS Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/macos/Build/Products/Release/EnjinWalletDaemon-${{github.ref_name}}-macos.zip